### ISSUE TITLE
[MCH] no longer does balance opener

### ISSUE THREAD

**Issue by timetowipe** [PunishXIV/WrathCombo#152] opened 2024-11-30 21:15 UTC
As of 1.0.0.4 full auto no longer follows the balance opener, which in turn throws off the entire rotation for the whole fight. 

I have included the log, the analysis, and the balance opener it used to follow pre 1.0.0.4

https://www.fflogs.com/reports/a:FHXCNmbxYLB4k69z#fight=4

https://xivanalysis.com/fflogs/a:FHXCNmbxYLB4k69z/4/138

What it should be doing: 
![Machinist_Standard_Opener_AA_6](https://github.com/user-attachments/assets/8e76f7b0-3ad2-43cf-9c24-1e45e4869684)

What it is doing now: 
![image](https://github.com/user-attachments/assets/877ee299-8788-46b3-bcce-ad6aa2b6bced)

**Comment by chaous2000** [comment] 2024-11-30 21:32
Found the problem, is was XIValexander. MCH in full auto worked perfectly fine with both bossmod setting at 26 & noclippy. 

With bossmod at 26:
https://www.fflogs.com/reports/a:Wp3HYAXw6L98cdyj#fight=5

https://xivanalysis.com/fflogs/a:Wp3HYAXw6L98cdyj/5/138

With noclippy:
https://www.fflogs.com/reports/a:3qhX2VLnpCtHQbMm#fight=6

https://xivanalysis.com/fflogs/a:3qhX2VLnpCtHQbMm/6/138

**Comment by Kagekazu** [comment] 2024-11-30 22:00
> Found the problem, is was XIValexander. MCH in full auto worked perfectly fine with both bossmod setting at 26 & noclippy.
> 
> With bossmod at 26: https://www.fflogs.com/reports/a:Wp3HYAXw6L98cdyj#fight=5
> 
> https://xivanalysis.com/fflogs/a:Wp3HYAXw6L98cdyj/5/138
> 
> With noclippy: https://www.fflogs.com/reports/a:3qhX2VLnpCtHQbMm#fight=6
> 
> https://xivanalysis.com/fflogs/a:3qhX2VLnpCtHQbMm/6/138

glad its solved! thanks for solving this one ^.^

**Comment by chaous2000** [comment] 2024-12-01 06:16
I realized after doing some fru that the /wrath combo off command does not persist through game resets, which i did not realize earlier when i *though* i figured out the problem. The actual root cause of the opener and rotation being way off is /wrath combo on. If i use this command so stuff isnt swapped on my hot bars, it completely ignores the balance opener and does whatever it wants. Logs and analysis from when i first opened the issue still stand.

**Comment by zbee** [comment] 2024-12-01 06:38
(clarifications in discord [here](https://discord.com/channels/1001823907193552978/1271175781569003590/1312667611003355156))

**Comment by Kagekazu** [comment] 2024-12-01 08:33
Isn't that more an issue cause of the command? And not really a mch issue? (I didn't look at the no swap command, so no clue how it works atm )

**Comment by Taurenkey** [comment] 2024-12-01 10:24
It is intended for the command to not persist as a permanent option, to lessen the headache where people forget they've messed about with it and then wonder why nothing works. If that's all I will close this now.

**Closed by Taurenkey** 2024-12-01 10:24 UTC
Labels: Fixes
