### ISSUE TITLE
[DRK] disesteem on advanced modes without cooldowns

### ISSUE THREAD

**Issue by hhharkness** [PunishXIV/WrathCombo#215] opened 2024-12-20 04:40 UTC
the option to add disesteem to the advanced modes is nested under cooldowns, which means you can't use it if you use the ogcd feature. would it be possible to have it separate, especially since it's not included in the ogcd feature anyway so it shouldn't cause any conflicts

**Comment by zbee** [comment] 2024-12-20 04:42
I will add it to the oGCD Feature.
Duplicate of #89.

**Closed by zbee** 2024-12-20 04:42 UTC
Labels: Duplicate, Suggestion
