### ISSUE TITLE
[Bug] Combo paging reverts to its starter option when other buttons are pressed.

### ISSUE THREAD

**Issue by t-l13** [PunishXIV/WrathCombo#93] opened 2024-11-22 13:27 UTC
There seems to be a bug when using a basic (note: not the in-mod Simple option) setup to only replace basic weapon combos, such as paging Gunbreaker, Dark Knight's, and Reaper's 123 combos. 

This seems to behave normally in most instances, but behaves strangely with certain actions. The plugin is possibly reading Weaponskills that don't break combos as breaking combos.

I have two examples of this: [Gunbreaker](https://gyazo.com/04694a6035d738762a8739cd9affb75c) and [Reaper](https://gyazo.com/f82f3d931ed1108175fc2961553fdad8)

For Gunbreaker, these are my settings:

- Advanced Mode - Single Target
- Advanced Mode - AoE

This seems to mostly be triggered by Gnashing Fang combo and Continuation.

For Reaper, these are my settings:

- Advanced Mode - Single Target
- Advanced Mode - AoE
- Enshroud to Communio to Perfectio Feature

This problem happens with both Slice combo and Communio--basically any time the plugin is paging a button, it seems. Many more buttons caused issues with this than on Gunbreaker: Executioner's GCDs, Plentiful Harvest, Enshroud GCDs--basically the button is flashing *all the time.*

I assume this is a broader error and not particularly class-specific, based on what I've seen.

**Comment by zbee** [comment] 2024-11-22 13:56
What you are seeing are changes implemented to Action Queuing to resolve a niche bug with intense mashing, which is actively preventing queued up-but-not-executed actions from affecting the combo code.
This is intended behavior, where we opted for combos executing as written over visuals of the button.

If you would like to make a GitHub issue for this #combo-issues post [here](https://discord.com/channels/1001823907193552978/1308172430568849468), or just add your voice there, to put your support behind it, perhaps this is something we eventually add as a solution.
Closing this as it is not an actual bug though.

**Closed by zbee** 2024-11-22 13:56 UTC
Labels: wontfix-notaproblem
